GET http://localhost:3000/users

###

GET http://localhost:3000/users?userName=Jer

###

POST http://localhost:3000/users
Content-Type: application/json

{
    "userName": "Test123"
}

###

DELETE http://localhost:3000/users/6217c53d4ff436151acda868

###

GET http://localhost:3000/products

###

POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "userName": "wowly",
    "email": "wowy@yahoo.com",
    "password": "12345678",
    "studentId": "1155112345"
}

###

POST http://localhost:3000/api/auth/signin
Content-Type: application/json

{
    "userName": "Jer",
    "password": "12345678"
}

###
POST http://localhost:3000/api/auth/signout

###

GET http://localhost:3000/api/test/user

###
GET http://localhost:3000/api/test/admin

###
GET http://localhost:3000/